### ISSUE TITLE
new issue no subtasks

### ISSUE THREAD

**Issue by iulia-b** [iulia-b/lalenatest#2]
Placeholder to revisit spacing and styling for task lists feature set before GA. 

**Style bugs**
- [ ] #2

- [ ] #1
- [ ] https://github.com/github/issues/issues/1590

- [ ] While trying to refactor tasklists, @iulia-b found some bugs where the unfurl does not work as expected with the updated markup.

**Other style tweaks**
- [ ] Increase spacing between drag handle and checkbox? Suggested by

cc @lukewar
